### ISSUE TITLE
Error when there is a local crate:

### ISSUE THREAD

**Issue by dsully** [shift-d/crates.nvim#3]
Given:
```
[dependencies]
clap = "2"
foo = { path = "crates/foo" }
```

This error is thrown:

```
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua .../packer/opt/crates.nvim/lua/crates/modules/core/show.lua:70: attempt to index local 'crate_info' (a nil value)
```

**Comment by n-shift** [comment]
Hello, thanks for submitting an issue! This should be fixed by 2c72b4f ; Try updating plugin.

**Comment by n-shift** [comment]
![изображение](https://user-images.githubusercontent.com/53366878/131255629-4bbaf068-376a-48d3-bfed-296590388d6e.png)

Here's output right after fix (with `unstable` option enabled)

**Comment by dsully** [comment]
Thanks. That commit has a lot of whitespace / formatting changes as well, so it's hard to tell what the actual fix was.

**Comment by n-shift** [comment]
https://github.com/shift-d/crates.nvim/commit/2c72b4f68ba025a1613c66b458544227468dbc9f#diff-95c4edb8de322d80a7d7c5b899231f9b4b51e6b49cc8898f0dff2085a621e10cR25-R28
